add validation

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -75,24 +75,28 @@ jobs:
     needs: [ "build", "test", "sonarcloud_analysis" ]
     runs-on: ubuntu-latest
     steps:
-      - # checkout to the repository on the build machine
-        name: Checkout
+      - name: Checkout
         uses: actions/checkout@v3
-      - # login to Docker Hub using the secrets provided
-        name: Login to Docker Hub
+
+      - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
-      - # create a build kit builder instance
-        name: Set up Docker Buildx
+
+      - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
-      - # build the container image and push it to Docker \
-        # Hub with the name clockbox.
-        name: Build and push
-        uses: docker/build-push-action@v4
-        with:
-          context: .
-          file: ./Dockerfile
-          push: true
-          tags: $/clockbox:latest
+
+      - name: Check Docker availability
+        run: |
+          docker --version
+          docker build -t desapp -f ./Dockerfile .
+          docker run -d -p 8080:8080 desapp
+          sleep 10
+          response=$(curl -sSf http://localhost:8080/ping)
+          if [[ "$response" == "pong" ]]; then
+            echo "Docker is available and responding to ping."
+          else
+            echo "Failed to start Docker or Docker container is not responding correctly."
+            exit 1
+          fi
